is - identity operator
used to check for memory location.

In [11]:
import numpy as np

a = np.array([1,2,3])
b = np.array([2,4,5])

print(a+b)
print(a-b)
print(a/b)
print(a//b)
print(a*b)
print(a**b)
print(a%b)

[3 6 8]
[-1 -2 -2]
[0.5 0.5 0.6]
[0 0 0]
[ 2  8 15]
[  1  16 243]
[1 2 3]


In [14]:
a = np.array([[1,2,3],[2,3,4]])
b = np.array([[2,3,4],[3,4,6]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)
np.dot(a,np.transpose(b))

[[ 3  5  7]
 [ 5  7 10]]
[[-1 -1 -1]
 [-1 -1 -2]]
[[ 2  6 12]
 [ 6 12 24]]
[[0.5        0.66666667 0.75      ]
 [0.66666667 0.75       0.66666667]]
[[0 0 0]
 [0 0 0]]
[[1 2 3]
 [2 3 4]]
[[   1    8   81]
 [   8   81 4096]]


array([[20, 29],
       [29, 42]])

In [18]:
a = np.array([[10,20,30],[5,10,15]])

print(np.min(a))
print(np.sum(a))
print(np.max(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

5
90
30
[15 30 45]
[60 30]
